version: '3.8'

services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: app
    restart: always
    working_dir: /var/www/
    volumes:
      - .:/var/www
  
  db:
    container_name: database
    image: mysql:8.0
    volumes:
      - ./docker/storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306